spring:
  cloud:
    function:
      definition: >-
        coffeeshopOrderStatusV1ReadySourceCountryStoreIdOrderIdConsumer;coffeeshopOrderStatusV1InprogressSourceCountryStoreIdOrderIdConsumer;coffeeshopOrderDetailsV1SourceCountryStoreIdOrderIdConsumer;coffeeshopOrderStatusV1OutofstockSourceCountryStoreIdOrderIdConsumer
    stream:
      bindings:
        coffeeshopOrderStatusV1ReadySourceCountryStoreIdOrderIdConsumer-in-0:
          destination: coffeeshop/order/status/v1/ready/*/*/*/*
        coffeeshopOrderStatusV1InprogressSourceCountryStoreIdOrderIdConsumer-in-0:
          destination: coffeeshop/order/status/v1/inprogress/*/*/*/*
        coffeeshopOrderDetailsV1SourceCountryStoreIdOrderIdConsumer-in-0:
          destination: coffeeshop/order/details/v1/*/*/*/*
        coffeeshopOrderStatusV1OutofstockSourceCountryStoreIdOrderIdConsumer-in-0:
          destination: coffeeshop/order/status/v1/outofstock/*/*/*/*
      binders:
        solace-binder:
          type: solace
          environment:
            solace:
              java:
                host: 'tcp://localhost:55554'
                msgVpn: default
                clientUsername: default
                clientPassword: default
logging:
  level:
    root: info
    org:
      springframework: info
server:
  port: 8089
management:
  endpoints:
    web:
      exposure:
        include: '*'

